routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Frontend Area - Start */

Route::get('/', 'FrontendController@landing');
Route::get('/donasi', 'FrontendController@donation')->name('fe.donate');
Route::post('/donasi', 'FrontendController@donationStore')->name('fe.donate.store');
Route::get('/konfirmasi-transfer', 'FrontendController@confirmation')->name('fe.confirmation');
Route::post('/konfirmasi-transfer', 'FrontendController@confirmationStore')->name('fe.confirmation.store');
Route::get('/kontak', 'FrontendController@contact')->name('fe.contact');
Route::post('/kontak', 'FrontendController@contactStore')->name('fe.contact.store');
Route::get('/gallery', 'FrontendController@galleryIndex')->name('fe.gallery');
Route::get('/post', 'FrontendController@postIndex')->name('fe.post');
Route::get('/post/{slug}', 'FrontendController@postShow')->name('fe.post.show');
Route::get('/halaman/{slug}', 'FrontendController@pageShow')->name('fe.page.show');
Route::get('/data-anak-panti', 'FrontendController@member')->name('fe.member');

/* Frontend Area - End */

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'main', 'middleware'=>'auth'], function () {

    Route::get('/gallery', 'GalleryController@index')->name('gallery.index')->middleware('role:admin');
    Route::delete('/gallery', 'GalleryController@destroy')->name('gallery.destroy')->middleware('role:admin');
    Route::post('/dropzone', 'GalleryController@dropZoneStore')->name('dropzone.store')->middleware('role:admin');
    Route::delete('/dropzone', 'GalleryController@dropZoneDestroy')->name('dropzone.destroy')->middleware('role:admin');

    Route::get('/confirmation', 'ConfirmationController@index')->name('confirmation.index')->middleware('role:admin');
    Route::patch('/confirmation/{id}/approve', 'ConfirmationController@approve')->name('confirmation.approve')->middleware('role:admin');
    Route::get('/confirmation/{id}/cancel', 'ConfirmationController@cancel')->name('confirmation.cancel')->middleware('role:admin');

    Route::get('/profile', 'UserController@showProfile')->name('profile.show');
    Route::patch('/profile', 'UserController@updateProfile')->name('profile.update');

    Route::resource('/page', 'PageController')->middleware('role:admin');
    Route::resource('/contact', 'ContactController')->middleware('role:admin');
    Route::resource('/category', 'CategoryController')->middleware('role:admin');
    Route::resource('/post', 'PostController')->middleware('role:admin');
    Route::resource('/bank', 'BankController')->middleware('role:admin');
    Route::resource('/donation', 'DonationController')->middleware('role:admin');
    Route::resource('/member', 'MemberController')->middleware('role:admin');
    Route::resource('/user', 'UserController')->middleware('role:admin');

    Route::get('/d/donation', 'DonaturController@indexDonation')->name('donation.index.d')->middleware('role:donatur');
    Route::get('/d/donation/create', 'DonaturController@createDonation')->name('donation.create.d')->middleware('role:donatur');
    Route::post('/d/donation', 'DonaturController@storeDonation')->name('donation.store.d')->middleware('role:donatur');
    Route::get('/d/donation/{id}/show', 'DonaturController@showDonation')->name('donation.show.d')->middleware('role:donatur');

    Route::get('/d/donation/{donation_id}/confirmation/create', 'DonaturController@createConfirmation')->name('confirmation.create.d')->middleware('role:donatur');
    Route::post('/d/donation/confirmation/store', 'DonaturController@storeConfirmation')->name('confirmation.store.d')->middleware('role:donatur');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $appends = ['display_status', 'display_date'];

    public function scopeGenerateSlug($query, $title)
    {
        $g_slug = str_slug($title);
        $slug_check = $this->where('slug', $g_slug)->count();
        if ($slug_check == 0) {
            $slug = $g_slug;
        } else {
            $check = 0;
            $unique = false;
            while ($unique == false) {
                $randomID = ++$check;
                $check = $this->where('slug', $g_slug.'-'.$randomID)->count();
                if ($check > 0) {
                    $unique = false;
                } else {
                    $unique = true;
                }
            }
            $slug = $g_slug.'-'.$randomID;
        }

        return $slug;
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function getDisplayStatusAttribute()
    {   
    	$value = $this->status;
        if ($value == 100) {
            $status = "Publish";
        } else if ($value == 10) {
            $status = "Draft";
        } else {
            $status = "Tidak Ada";
        }
        
        return $status;
    }

    public function getDisplayDateAttribute()
    {
        $value = $this->attributes['created_at'];

        $result = date('d-m-Y', strtotime($value));
        
        return $result;
    }

    public function scopeLatestPost($query, $limit)
    {
        return $query->orderBy('id', 'dsc')->limit($limit);
    }

    public function scopeActive($query)
    {
        return $query->where('status', 100);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Yajra\Datatables\Datatables;
use App\Category;
use App\Post;
use Session;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $posts = Post::with('category', 'user');

            if ($request->get('category') != null) {
                if ($request->category != 'all') {
                    $posts->where('category_id', $request->category);
                }
            }

            $posts = $posts->select('*');
            
            return Datatables::of($posts)
                ->addIndexColumn()
                ->addColumn('action', function($post){
                    return view('partials._action', [
                        'model'           => $post,
                        'form_url'        => route('post.destroy', $post->id),
                        'edit_url'        => route('post.edit', $post->id),
                        'show_url'        => route('post.show', $post->id)
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('posts.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'title' => 'required|string|max:255',
          'content' => 'required',
          'category_id' => 'required|numeric',
          'image' => 'required|image|max:2048'
        ]);
        
        $post = new Post;
        $post->user_id = \Auth::user()->id;
        $post->category_id = $request->category_id;
        $post->title = $request->title;
        $post->slug = Post::generateSlug($request->title);
        $post->content = $request->content;

        if ($request->hasFile('image')) {
            // megnambil image yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_image = $request->file('image');
            $extension = $uploaded_image->getClientOriginalExtension();
            // membuat nama file random dengan extension
            $filename = md5(time()) . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'posts';
            // memindahkan file ke folder public/images
            $uploaded_image->move($destinationPath, $filename);

            // save nama field image
            $post->image = $filename;
        }

        $post->save();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Artikel dengan judul $post->title berhasil dibuat"
        ]);
        
        return redirect()->route('post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);

        return view('posts.show')->with(compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);

        return view('posts.edit')->with(compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
          'title' => 'required|string|max:255',
          'content' => 'required',
          'category_id' => 'required|numeric',
          'image' => 'image|max:2048'
        ]);
        
        $post = Post::find($id);
        $post->user_id = \Auth::user()->id;
        $post->category_id = $request->category_id;
        $post->title = $request->title;
        $post->content = $request->content;

        if ($post->title != $request->title) {
            $post->slug = Post::generateSlug($request->title);
        }

        if ($request->hasFile('image')) {
            // megnambil image yang diupload berikut ekstensinya
            $filename = null;
            $uploaded_image = $request->file('image');
            $extension = $uploaded_image->getClientOriginalExtension();
            // membuat nama file random dengan extension
            $filename = md5(time()) . '.' . $extension;
            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'posts';
            // memindahkan file ke folder public/images
            $uploaded_image->move($destinationPath, $filename);
            // hapus image lama, jika ada
            if ($post->image) {
                $old_image = $post->image;
                $filepath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'posts'
                 . DIRECTORY_SEPARATOR . $post->image;
                try {
                    File::delete($filepath);
                } catch (FileNotFoundException $e) {
                    // File sudah dihapus/tidak ada
                }
            }
            // ganti field image dengan image yang baru
            $post->image = $filename;
        }

        $post->save();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Artikel dengan judul $post->title berhasil diedit"
        ]);
        
        return redirect()->route('post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);

        if ($post->image) {
            $filepath = public_path() . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'posts'
             . DIRECTORY_SEPARATOR . $post->image;
            try {
                File::delete($filepath);
            } catch (FileNotFoundException $e) {
                // File sudah dihapus/tidak ada
            }
        }

        $post->delete();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menghapus data"
        ]);

        return redirect()->route('post.index');
    }
}

resources/views/posts/create.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Artikel</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Tambah Artikel</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
              <label for="title">Judul Artikel</label>
              <input id="title" type="text" class="form-control @if ($errors->has('title')) is-invalid @endif" name="title" tabindex="1" value="{{ old('title') }}">
              @if ($errors->has('title'))
                <div class="invalid-feedback">
                  {{ $errors->first('title') }}
                </div>
              @endif
            </div>

            <label for="image">Gambar</label>
            <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }} custom-file mb-3">
              <input id="image" type="file" class="custom-file-input @if ($errors->has('image')) is-invalid @endif" name="image" tabindex="1">
              <label class="custom-file-label" for="customFile">Pilih Gambar</label>
              @if ($errors->has('image'))
                <div class="invalid-feedback">
                  {{ $errors->first('image') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('category_id') ? ' has-error' : '' }}">
              <label for="category_id">Kategori</label>
              <select name="category_id" class="form-control">
                @foreach (\App\Category::all() as $item)
                  <option value="{{$item->id}}">{{$item->name}}</option>
                @endforeach
              </select>
              @if ($errors->has('category_id'))
                <div class="invalid-feedback">
                  {{ $errors->first('category_id') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('content') ? ' has-error' : '' }}">
              <label for="content">Konten</label>
              <textarea class="form-control @if ($errors->has('content')) is-invalid @endif" name="content" tabindex="1">{{ old('content') }}</textarea>
              @if ($errors->has('content'))
                <div class="invalid-feedback">
                  {{ $errors->first('content') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="4">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
    $('textarea').trumbowyg({
        lang: 'id'
    });
  </script>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Artikel</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Edit Artikel</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('post.update', $post->id) }}" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PUT') }}

            <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
              <label for="title">Judul Artikel</label>
              <input id="title" type="text" class="form-control @if ($errors->has('title')) is-invalid @endif" name="title" tabindex="1" value="{{ $post->title }}">
              @if ($errors->has('title'))
                <div class="invalid-feedback">
                  {{ $errors->first('title') }}
                </div>
              @endif
            </div>

            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
              <label for="image">Gambar</label>
              @if (!is_null($post->image))
                <img src="{{asset('uploads/images/posts/'.$post->image)}}" class="rounded d-block" width="300" alt="image">
              @endif
              <br>
              <i class="small">** Maximum size gambar yang di upload adalah 2MB</i><br>
            </div>

            <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }} custom-file mb-3">
              <input id="image" type="file" class="custom-file-input @if ($errors->has('image')) is-invalid @endif" name="image" tabindex="1">
              <label class="custom-file-label" for="customFile">Pilih Gambar</label>
              @if ($errors->has('image'))
                <div class="invalid-feedback">
                  {{ $errors->first('image') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('category_id') ? ' has-error' : '' }}">
              <label for="category_id">Kategori</label>
              <select name="category_id" class="form-control">
                @foreach (\App\Category::all() as $item)
                  <option value="{{$item->id}}" @if ($post->category_id == $item->id) selected @endif>{{$item->name}}</option>
                @endforeach
              </select>
              @if ($errors->has('category_id'))
                <div class="invalid-feedback">
                  {{ $errors->first('category_id') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('content') ? ' has-error' : '' }}">
              <label for="content">Konten</label>
              <textarea class="form-control @if ($errors->has('content')) is-invalid @endif" name="content" tabindex="1">{!! $post->content !!}</textarea>
              @if ($errors->has('content'))
                <div class="invalid-feedback">
                  {{ $errors->first('content') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="4">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
    $('textarea').trumbowyg({
        lang: 'id'
    });
  </script>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-start mb-4">
    <h1 class="h3 mb-0 text-gray-800">Artikel</h1>
    <a class="btn btn-sm btn-primary mr-auto ml-4" href="{{ route('post.create') }}"><i class="fa fa-plus"></i> Tambah Artikel</a> 
    <div class="form-inline">
      <label for="filter">Filter Kategori</label>
      <select name="category" class="form-control-sm ml-2">
        <option value="all">Semua</option>
        @foreach (\App\Category::all() as $item)
          <option value="{{$item->id}}">{{$item->name}}</option>
        @endforeach
      </select>
      <button class="btn btn-sm btn-primary ml-2" id="btn-filter"><i class="fas fa-filter"></i></button>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">List Artikel</h6>
        </div>
        <div class="card-body">

        <div class="table-responsive">
          <table class="table table-hover table-bordered datatable">
            <thead>                                 
              <tr>
                <th>#</th>
                <th>Judul</th>
                <th>Kategori</th>
                <th>Penulis</th>
                <th>Tanggal Publish</th>
                <th>Status</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>

        </div>
      </div>
    </div>
  </div>
@endsection
@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          language: {
              url: '{{ asset('vendor/sb-temp/vendor/datatables/lang/Indonesian.json') }}'
          },
          ajax: {
            url: '{{ route('post.index') }}',
            data: function (d) {
              d.category = $('select[name=category]').val()
            }
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'title', name: 'title'},
            {data: 'category.name', name: 'category.name'},
            {data: 'user.name', name: 'user.name'},
            {data: 'display_date', name: 'display_date', orderable: false, searchable: false},
            {data: 'display_status', name: 'display_status', orderable: false, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $('#btn-filter').click(function(){
         $('.datatable').DataTable().draw(true);
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });
</script>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Artikel</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Lihat Artikel</h6>
        </div>
        <div class="card-body">
          
          <p>
            Judul: <br><strong>{{$post->title}}</strong>
            <hr>
          </p>
          <p>
            Penulis: <br><strong>{{$post->user->name}}</strong>
            <hr>
          </p>
          <p>
            Kategori: <br><strong>{{$post->category->name}}</strong>
            <hr>
          </p>
          <p>
            Tanggal Publish: <br><strong>{{$post->display_date}}</strong>
            <hr>
          </p>
          <p>
            Gambar: <br><img src="{{asset('uploads/images/posts/'.$post->image)}}" class="rounded d-block" alt="image" style="max-width: 500px;">
            <hr>
          </p>
          <p>
            Isi Konten: <br>{!! $post->content !!}
          </p>

        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
    $('textarea').trumbowyg({
        lang: 'id'
    });
  </script>
@endsection