routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Frontend Area - Start */

Route::get('/', 'FrontendController@landing');
Route::get('/donasi', 'FrontendController@donation')->name('fe.donate');
Route::post('/donasi', 'FrontendController@donationStore')->name('fe.donate.store');
Route::get('/konfirmasi-transfer', 'FrontendController@confirmation')->name('fe.confirmation');
Route::post('/konfirmasi-transfer', 'FrontendController@confirmationStore')->name('fe.confirmation.store');
Route::get('/kontak', 'FrontendController@contact')->name('fe.contact');
Route::post('/kontak', 'FrontendController@contactStore')->name('fe.contact.store');
Route::get('/gallery', 'FrontendController@galleryIndex')->name('fe.gallery');
Route::get('/post', 'FrontendController@postIndex')->name('fe.post');
Route::get('/post/{slug}', 'FrontendController@postShow')->name('fe.post.show');
Route::get('/halaman/{slug}', 'FrontendController@pageShow')->name('fe.page.show');
Route::get('/data-anak-panti', 'FrontendController@member')->name('fe.member');

/* Frontend Area - End */

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'main', 'middleware'=>'auth'], function () {

    Route::get('/gallery', 'GalleryController@index')->name('gallery.index')->middleware('role:admin');
    Route::delete('/gallery', 'GalleryController@destroy')->name('gallery.destroy')->middleware('role:admin');
    Route::post('/dropzone', 'GalleryController@dropZoneStore')->name('dropzone.store')->middleware('role:admin');
    Route::delete('/dropzone', 'GalleryController@dropZoneDestroy')->name('dropzone.destroy')->middleware('role:admin');

    Route::get('/confirmation', 'ConfirmationController@index')->name('confirmation.index')->middleware('role:admin');
    Route::patch('/confirmation/{id}/approve', 'ConfirmationController@approve')->name('confirmation.approve')->middleware('role:admin');
    Route::get('/confirmation/{id}/cancel', 'ConfirmationController@cancel')->name('confirmation.cancel')->middleware('role:admin');

    Route::get('/profile', 'UserController@showProfile')->name('profile.show');
    Route::patch('/profile', 'UserController@updateProfile')->name('profile.update');

    Route::resource('/page', 'PageController')->middleware('role:admin');
    Route::resource('/contact', 'ContactController')->middleware('role:admin');
    Route::resource('/category', 'CategoryController')->middleware('role:admin');
    Route::resource('/post', 'PostController')->middleware('role:admin');
    Route::resource('/bank', 'BankController')->middleware('role:admin');
    Route::resource('/donation', 'DonationController')->middleware('role:admin');
    Route::resource('/member', 'MemberController')->middleware('role:admin');
    Route::resource('/user', 'UserController')->middleware('role:admin');

    Route::get('/d/donation', 'DonaturController@indexDonation')->name('donation.index.d')->middleware('role:donatur');
    Route::get('/d/donation/create', 'DonaturController@createDonation')->name('donation.create.d')->middleware('role:donatur');
    Route::post('/d/donation', 'DonaturController@storeDonation')->name('donation.store.d')->middleware('role:donatur');
    Route::get('/d/donation/{id}/show', 'DonaturController@showDonation')->name('donation.show.d')->middleware('role:donatur');

    Route::get('/d/donation/{donation_id}/confirmation/create', 'DonaturController@createConfirmation')->name('confirmation.create.d')->middleware('role:donatur');
    Route::post('/d/donation/confirmation/store', 'DonaturController@storeConfirmation')->name('confirmation.store.d')->middleware('role:donatur');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $appends = ['display_status'];

    public function getDisplayStatusAttribute()
    {   
    	$value = $this->status;
        if ($value == 100) {
            $status = "Aktif";
        } else if ($value == 10) {
            $status = "Non Aktif";
        } else {
            $status = "Tidak Ada";
        }
        
        return $status;
    }

    public function scopeActive($query)
    {
        return $query->where('status', 100);
    }

    public function scopeGenerateSlug($query, $name)
    {
        $g_slug = str_slug($name);
        $slug_check = $this->where('slug', $g_slug)->count();
        if ($slug_check == 0) {
            $slug = $g_slug;
        } else {
            $check = 0;
            $unique = false;
            while ($unique == false) {
                $randomID = ++$check;
                $check = $this->where('slug', $g_slug.'-'.$randomID)->count();
                if ($check > 0) {
                    $unique = false;
                } else {
                    $unique = true;
                }
            }
            $slug = $g_slug.'-'.$randomID;
        }

        return $slug;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use App\Category;
use Session;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $categories = Category::query();

            $categories = $categories->select('*');
            
            return Datatables::of($categories)
                ->addIndexColumn()
                ->addColumn('action', function($category){
                    return view('partials._action', [
                        'model'           => $category,
                        'form_url'        => route('category.destroy', $category->id),
                        'edit_url'        => route('category.edit', $category->id)
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create'); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'name' => 'required|string|max:255',
          'description' => 'required|string',
          'status' => 'required|numeric',
        ]);
        
        $category = new Category;
        $category->name = $request->name;
        $category->slug = Category::generateSlug($request->name);
        $category->description = $request->description;
        $category->status = $request->status;
        $category->save();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Kategori dengan nama $category->name berhasil dibuat"
        ]);
        
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);

        return view('categories.edit')->with(compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
          'name' => 'required|string|max:255',
          'description' => 'required|string',
          'status' => 'required|numeric',
        ]);
        
        $category = Category::find($id);
        $category->name = $request->name;
        $category->description = $request->description;
        $category->status = $request->status;

        if ($category->name != $request->name) {
            $category->slug = Category::generateSlug($request->name);
        }

        $category->save();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Kategori dengan nama $category->name berhasil diedit"
        ]);
        
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);

        $check = \App\Post::where('category_id', $id)->count();

        if ($check > 0) {
            Session::flash("flash_notification", [
                "level"=>"warning",
                "message"=>"Tidak dapat menghapus kategori yang sudah memiliki data artikel!"
            ]);

            return redirect()->back();
        }

        $category->delete();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menghapus data"
        ]);

        return redirect()->route('category.index');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Kategori</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Tambah Kategori</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('category.store') }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
              <label for="name">Nama Kategori</label>
              <input id="name" type="text" class="form-control @if ($errors->has('name')) is-invalid @endif" name="name" tabindex="1" value="{{ old('name') }}">
              @if ($errors->has('name'))
                <div class="invalid-feedback">
                  {{ $errors->first('name') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
              <label for="description">Deskripsi</label>
              <input id="description" type="text" class="form-control @if ($errors->has('description')) is-invalid @endif" name="description" tabindex="1" value="{{ old('description') }}">
              @if ($errors->has('description'))
                <div class="invalid-feedback">
                  {{ $errors->first('description') }}
                </div>
              @endif
            </div>
         
            <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
              <label for="status">Status</label>
              <select name="status" class="form-control">
                <option value="100">Aktif</option>
                <option value="10">Non Aktif</option>
              </select>
              @if ($errors->has('status'))
                <div class="invalid-feedback">
                  {{ $errors->first('status') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="4">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Kategori</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Edit Kategori</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('category.update', $category->id) }}" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PUT') }}

            <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
              <label for="name">Nama Kategori</label>
              <input id="name" type="text" class="form-control @if ($errors->has('name')) is-invalid @endif" name="name" tabindex="1" value="{{ $category->name }}">
              @if ($errors->has('name'))
                <div class="invalid-feedback">
                  {{ $errors->first('name') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
              <label for="description">Deskripsi </label>
              <input id="description" type="text" class="form-control @if ($errors->has('description')) is-invalid @endif" name="description" tabindex="1" value="{{ $category->description }}">
              @if ($errors->has('description'))
                <div class="invalid-feedback">
                  {{ $errors->first('description') }}
                </div>
              @endif
            </div>
         
            <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
              <label for="status">Status</label>
              <select name="status" class="form-control">
                <option value="100" @if ($category->status == "100") selected @endif>Aktif</option>
                <option value="10" @if ($category->status == "10") selected @endif>Non Aktif</option>
              </select>
              @if ($errors->has('status'))
                <div class="invalid-feedback">
                  {{ $errors->first('status') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="4">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-start mb-4">
    <h1 class="h3 mb-0 text-gray-800">Kategori</h1>
    <a class="btn btn-sm btn-primary mr-auto ml-4" href="{{ route('category.create') }}"><i class="fa fa-plus"></i> Tambah Kategori</a> 
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">List Kategori</h6>
        </div>
        <div class="card-body">

        <div class="table-responsive">
          <table class="table table-hover table-bordered datatable">
            <thead>                                 
              <tr>
                <th>#</th>
                <th>Nama Kategori</th>
                <th>Deskripsi</th>
                <th>Status</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>

        </div>
      </div>
    </div>
  </div>
@endsection
@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          language: {
              url: '{{ asset('vendor/sb-temp/vendor/datatables/lang/Indonesian.json') }}'
          },
          ajax: {
            url: '{{ route('category.index') }}',
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'name', name: 'name'},
            {data: 'description', name: 'description'},
            {data: 'display_status', name: 'display_status', orderable: false, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });
</script>
@endsection