routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Frontend Area - Start */

Route::get('/', 'FrontendController@landing');
Route::get('/donasi', 'FrontendController@donation')->name('fe.donate');
Route::post('/donasi', 'FrontendController@donationStore')->name('fe.donate.store');
Route::get('/konfirmasi-transfer', 'FrontendController@confirmation')->name('fe.confirmation');
Route::post('/konfirmasi-transfer', 'FrontendController@confirmationStore')->name('fe.confirmation.store');
Route::get('/kontak', 'FrontendController@contact')->name('fe.contact');
Route::post('/kontak', 'FrontendController@contactStore')->name('fe.contact.store');
Route::get('/gallery', 'FrontendController@galleryIndex')->name('fe.gallery');
Route::get('/post', 'FrontendController@postIndex')->name('fe.post');
Route::get('/post/{slug}', 'FrontendController@postShow')->name('fe.post.show');
Route::get('/halaman/{slug}', 'FrontendController@pageShow')->name('fe.page.show');
Route::get('/data-anak-panti', 'FrontendController@member')->name('fe.member');

/* Frontend Area - End */

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'main', 'middleware'=>'auth'], function () {

    Route::get('/gallery', 'GalleryController@index')->name('gallery.index')->middleware('role:admin');
    Route::delete('/gallery', 'GalleryController@destroy')->name('gallery.destroy')->middleware('role:admin');
    Route::post('/dropzone', 'GalleryController@dropZoneStore')->name('dropzone.store')->middleware('role:admin');
    Route::delete('/dropzone', 'GalleryController@dropZoneDestroy')->name('dropzone.destroy')->middleware('role:admin');

    Route::get('/confirmation', 'ConfirmationController@index')->name('confirmation.index')->middleware('role:admin');
    Route::patch('/confirmation/{id}/approve', 'ConfirmationController@approve')->name('confirmation.approve')->middleware('role:admin');
    Route::get('/confirmation/{id}/cancel', 'ConfirmationController@cancel')->name('confirmation.cancel')->middleware('role:admin');

    Route::get('/profile', 'UserController@showProfile')->name('profile.show');
    Route::patch('/profile', 'UserController@updateProfile')->name('profile.update');

    Route::resource('/page', 'PageController')->middleware('role:admin');
    Route::resource('/contact', 'ContactController')->middleware('role:admin');
    Route::resource('/category', 'CategoryController')->middleware('role:admin');
    Route::resource('/post', 'PostController')->middleware('role:admin');
    Route::resource('/bank', 'BankController')->middleware('role:admin');
    Route::resource('/donation', 'DonationController')->middleware('role:admin');
    Route::resource('/member', 'MemberController')->middleware('role:admin');
    Route::resource('/user', 'UserController')->middleware('role:admin');

    Route::get('/d/donation', 'DonaturController@indexDonation')->name('donation.index.d')->middleware('role:donatur');
    Route::get('/d/donation/create', 'DonaturController@createDonation')->name('donation.create.d')->middleware('role:donatur');
    Route::post('/d/donation', 'DonaturController@storeDonation')->name('donation.store.d')->middleware('role:donatur');
    Route::get('/d/donation/{id}/show', 'DonaturController@showDonation')->name('donation.show.d')->middleware('role:donatur');

    Route::get('/d/donation/{donation_id}/confirmation/create', 'DonaturController@createConfirmation')->name('confirmation.create.d')->middleware('role:donatur');
    Route::post('/d/donation/confirmation/store', 'DonaturController@storeConfirmation')->name('confirmation.store.d')->middleware('role:donatur');
});

app/Bank.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
	protected $appends = ['display_status'];

    public function getDisplayStatusAttribute()
    {   
    	$value = $this->status;
        if ($value == 100) {
            $status = "Aktif";
        } else if ($value == 0) {
            $status = "Non Aktif";
        } else {
            $status = "Tidak Ada";
        }
        
        return $status;
    }
}

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use App\Bank;
use Session;

class BankController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $banks = Bank::query();

            $banks = $banks->select('*');
            
            return Datatables::of($banks)
                ->addIndexColumn()
                ->addColumn('action', function($bank){
                    return view('partials._action', [
                        'model'           => $bank,
                        'form_url'        => route('bank.destroy', $bank->id),
                        'edit_url'        => route('bank.edit', $bank->id)
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('banks.index'); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('banks.create'); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'name' => 'required|string|max:255',
          'account_number' => 'required|numeric',
          'account_holder' => 'required|string',
          'status' => 'required|numeric',
        ]);
        
        $bank = new Bank;
        $bank->name = $request->name;
        $bank->account_number = $request->account_number;
        $bank->account_holder = $request->account_holder;
        $bank->status = $request->status;
        $bank->save();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Bank dengan nama $bank->name berhasil dibuat"
        ]);
        
        return redirect()->route('bank.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bank = Bank::find($id);

        return view('banks.edit')->with(compact('bank'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
          'name' => 'required|string|max:255',
          'account_number' => 'required|numeric',
          'account_holder' => 'required|string',
          'status' => 'required|numeric',
        ]);
        
        $bank = Bank::find($id);
        $bank->name = $request->name;
        $bank->account_number = $request->account_number;
        $bank->account_holder = $request->account_holder;
        $bank->status = $request->status;
        $bank->save();

        Session::flash("flash_notification", [
          "level"=>"success",
          "message"=>"Bank dengan nama $bank->name berhasil diedit"
        ]);
        
        return redirect()->route('bank.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $bank = Bank::find($id);

        $check = \App\Donation::where('bank_id', $id)->count();

        if ($check > 0) {
            Session::flash("flash_notification", [
                "level"=>"warning",
                "message"=>"Tidak dapat menghapus bank yang sudah memiliki data donasi!"
            ]);

            return redirect()->back();
        }

        $bank->delete();

        Session::flash("flash_notification", [
            "level"=>"success",
            "message"=>"Berhasil menghapus data"
        ]);

        return redirect()->route('bank.index');
    }
}

resources/views/banks/create.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Bank</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Tambah Bank</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('bank.store') }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
              <label for="name">Nama Bank</label>
              <input id="name" type="text" class="form-control @if ($errors->has('name')) is-invalid @endif" name="name" tabindex="1" value="{{ old('name') }}">
              @if ($errors->has('name'))
                <div class="invalid-feedback">
                  {{ $errors->first('name') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('account_number') ? ' has-error' : '' }}">
              <label for="account_number">Nomor Rekening</label>
              <input id="account_number" type="number" class="form-control @if ($errors->has('account_number')) is-invalid @endif" name="account_number" tabindex="1" value="{{ old('account_number') }}">
              @if ($errors->has('account_number'))
                <div class="invalid-feedback">
                  {{ $errors->first('account_number') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('account_holder') ? ' has-error' : '' }}">
              <label for="account_holder">Atas Nama Rekening</label>
              <input id="account_holder" type="text" class="form-control @if ($errors->has('account_holder')) is-invalid @endif" name="account_holder" tabindex="1" value="{{ old('account_holder') }}">
              @if ($errors->has('account_holder'))
                <div class="invalid-feedback">
                  {{ $errors->first('account_holder') }}
                </div>
              @endif
            </div>
         
            <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
              <label for="status">Status</label>
              <select name="status" class="form-control">
                <option value="100">Aktif</option>
                <option value="0">Non Aktif</option>
              </select>
              @if ($errors->has('status'))
                <div class="invalid-feedback">
                  {{ $errors->first('status') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="4">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/banks/edit.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Bank</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Edit Bank</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('bank.update', $bank->id) }}" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PUT') }}

            <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
              <label for="name">Nama Bank</label>
              <input id="name" type="text" class="form-control @if ($errors->has('name')) is-invalid @endif" name="name" tabindex="1" value="{{ $bank->name }}">
              @if ($errors->has('name'))
                <div class="invalid-feedback">
                  {{ $errors->first('name') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('account_number') ? ' has-error' : '' }}">
              <label for="account_number">Nomor Rekening</label>
              <input id="account_number" type="number" class="form-control @if ($errors->has('account_number')) is-invalid @endif" name="account_number" tabindex="1" value="{{ $bank->account_number }}">
              @if ($errors->has('account_number'))
                <div class="invalid-feedback">
                  {{ $errors->first('account_number') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('account_holder') ? ' has-error' : '' }}">
              <label for="account_holder">Atas Nama Rekening</label>
              <input id="account_holder" type="text" class="form-control @if ($errors->has('account_holder')) is-invalid @endif" name="account_holder" tabindex="1" value="{{ $bank->account_holder }}">
              @if ($errors->has('account_holder'))
                <div class="invalid-feedback">
                  {{ $errors->first('account_holder') }}
                </div>
              @endif
            </div>
         
            <div class="form-group {{ $errors->has('status') ? ' has-error' : '' }}">
              <label for="status">Status</label>
              <select name="status" class="form-control">
                <option value="100" @if ($bank->status == "100") selected @endif>Aktif</option>
                <option value="0" @if ($bank->status == "0") selected @endif>Non Aktif</option>
              </select>
              @if ($errors->has('status'))
                <div class="invalid-feedback">
                  {{ $errors->first('status') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="4">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/banks/index.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-start mb-4">
    <h1 class="h3 mb-0 text-gray-800">Bank</h1>
    <a class="btn btn-sm btn-primary mr-auto ml-4" href="{{ route('bank.create') }}"><i class="fa fa-plus"></i> Tambah Bank</a> 
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">List Bank</h6>
        </div>
        <div class="card-body">

        <div class="table-responsive">
          <table class="table table-hover table-bordered datatable">
            <thead>                                 
              <tr>
                <th>#</th>
                <th>Nama Bank</th>
                <th>Nomor Rekening</th>
                <th>Atas Nama Rekening</th>
                <th>Status</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>

        </div>
      </div>
    </div>
  </div>
@endsection
@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          language: {
              url: '{{ asset('vendor/sb-temp/vendor/datatables/lang/Indonesian.json') }}'
          },
          ajax: {
            url: '{{ route('bank.index') }}',
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'name', name: 'name'},
            {data: 'account_number', name: 'account_number'},
            {data: 'account_holder', name: 'account_holder'},
            {data: 'display_status', name: 'display_status', orderable: false, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $('#btn-filter').click(function(){
         $('.datatable').DataTable().draw(true);
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });
</script>
@endsection