routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Frontend Area - Start */

Route::get('/', 'FrontendController@landing');
Route::get('/donasi', 'FrontendController@donation')->name('fe.donate');
Route::post('/donasi', 'FrontendController@donationStore')->name('fe.donate.store');
Route::get('/konfirmasi-transfer', 'FrontendController@confirmation')->name('fe.confirmation');
Route::post('/konfirmasi-transfer', 'FrontendController@confirmationStore')->name('fe.confirmation.store');
Route::get('/kontak', 'FrontendController@contact')->name('fe.contact');
Route::post('/kontak', 'FrontendController@contactStore')->name('fe.contact.store');
Route::get('/gallery', 'FrontendController@galleryIndex')->name('fe.gallery');
Route::get('/post', 'FrontendController@postIndex')->name('fe.post');
Route::get('/post/{slug}', 'FrontendController@postShow')->name('fe.post.show');
Route::get('/halaman/{slug}', 'FrontendController@pageShow')->name('fe.page.show');
Route::get('/data-anak-panti', 'FrontendController@member')->name('fe.member');

/* Frontend Area - End */

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'main', 'middleware'=>'auth'], function () {

    Route::get('/gallery', 'GalleryController@index')->name('gallery.index')->middleware('role:admin');
    Route::delete('/gallery', 'GalleryController@destroy')->name('gallery.destroy')->middleware('role:admin');
    Route::post('/dropzone', 'GalleryController@dropZoneStore')->name('dropzone.store')->middleware('role:admin');
    Route::delete('/dropzone', 'GalleryController@dropZoneDestroy')->name('dropzone.destroy')->middleware('role:admin');

    Route::get('/confirmation', 'ConfirmationController@index')->name('confirmation.index')->middleware('role:admin');
    Route::patch('/confirmation/{id}/approve', 'ConfirmationController@approve')->name('confirmation.approve')->middleware('role:admin');
    Route::get('/confirmation/{id}/cancel', 'ConfirmationController@cancel')->name('confirmation.cancel')->middleware('role:admin');

    Route::get('/profile', 'UserController@showProfile')->name('profile.show');
    Route::patch('/profile', 'UserController@updateProfile')->name('profile.update');

    Route::resource('/page', 'PageController')->middleware('role:admin');
    Route::resource('/contact', 'ContactController')->middleware('role:admin');
    Route::resource('/category', 'CategoryController')->middleware('role:admin');
    Route::resource('/post', 'PostController')->middleware('role:admin');
    Route::resource('/bank', 'BankController')->middleware('role:admin');
    Route::resource('/donation', 'DonationController')->middleware('role:admin');
    Route::resource('/member', 'MemberController')->middleware('role:admin');
    Route::resource('/user', 'UserController')->middleware('role:admin');

    Route::get('/d/donation', 'DonaturController@indexDonation')->name('donation.index.d')->middleware('role:donatur');
    Route::get('/d/donation/create', 'DonaturController@createDonation')->name('donation.create.d')->middleware('role:donatur');
    Route::post('/d/donation', 'DonaturController@storeDonation')->name('donation.store.d')->middleware('role:donatur');
    Route::get('/d/donation/{id}/show', 'DonaturController@showDonation')->name('donation.show.d')->middleware('role:donatur');

    Route::get('/d/donation/{donation_id}/confirmation/create', 'DonaturController@createConfirmation')->name('confirmation.create.d')->middleware('role:donatur');
    Route::post('/d/donation/confirmation/store', 'DonaturController@storeConfirmation')->name('confirmation.store.d')->middleware('role:donatur');
});

resources/views/pages/create.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Halaman</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Tambah Halaman</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('page.store') }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
              <label for="title">Judul Halaman</label>
              <input id="title" type="text" class="form-control @if ($errors->has('title')) is-invalid @endif" name="title" tabindex="1" value="{{ old('title') }}">
              @if ($errors->has('title'))
                <div class="invalid-feedback">
                  {{ $errors->first('title') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('content') ? ' has-error' : '' }}">
              <label for="content">Konten</label>
              <textarea class="form-control @if ($errors->has('content')) is-invalid @endif" name="content" tabindex="1">{{ old('content') }}</textarea>
              @if ($errors->has('content'))
                <div class="invalid-feedback">
                  {{ $errors->first('content') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="4">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
    $('textarea').trumbowyg({
        lang: 'id'
    });
  </script>
@endsection

resources/views/pages/edit.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Halaman</h1>
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Edit Halaman</h6>
        </div>
        <div class="card-body">
          
          <form method="POST" action="{{ route('page.update', $page->id) }}" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PUT') }}

            <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
              <label for="title">Judul Halaman</label>
              <input id="title" type="text" class="form-control @if ($errors->has('title')) is-invalid @endif" name="title" tabindex="1" value="{{ $page->title }}">
              @if ($errors->has('title'))
                <div class="invalid-feedback">
                  {{ $errors->first('title') }}
                </div>
              @endif
            </div>

            <div class="form-group {{ $errors->has('content') ? ' has-error' : '' }}">
              <label for="content">Konten</label>
              <textarea class="form-control @if ($errors->has('content')) is-invalid @endif" name="content" tabindex="1">{!! $page->content !!}</textarea>
              @if ($errors->has('content'))
                <div class="invalid-feedback">
                  {{ $errors->first('content') }}
                </div>
              @endif
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" tabindex="4">
                Simpan
              </button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
    $('textarea').trumbowyg({
        lang: 'id'
    });
  </script>
@endsection

resources/views/pages/index.blade.php
@extends('layouts.main')

@section('content')
  <div class="d-sm-flex align-items-center justify-content-start mb-4">
    <h1 class="h3 mb-0 text-gray-800">Halaman</h1>
    <a class="btn btn-sm btn-primary mr-auto ml-4" href="{{ route('page.create') }}"><i class="fa fa-plus"></i> Tambah Halaman</a> 
  </div>

  <div class="row">
    <div class="col-lg-12">

      <!-- Basic Card Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">List Halaman</h6>
        </div>
        <div class="card-body">

        <div class="table-responsive">
          <table class="table table-hover table-bordered datatable">
            <thead>                                 
              <tr>
                <th>#</th>
                <th>Judul</th>
                <th>Penulis</th>
                <th>Tanggal Publish</th>
                <th>Status</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        </div>

        </div>
      </div>
    </div>
  </div>
@endsection
@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          language: {
              url: '{{ asset('vendor/sb-temp/vendor/datatables/lang/Indonesian.json') }}'
          },
          ajax: {
            url: '{{ route('page.index') }}',
            data: function (d) {
              d.category = $('select[name=category]').val()
            }
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'title', name: 'title'},
            {data: 'user.name', name: 'user.name'},
            {data: 'display_date', name: 'display_date', orderable: false, searchable: false},
            {data: 'display_status', name: 'display_status', orderable: false, searchable: false},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $('#btn-filter').click(function(){
         $('.datatable').DataTable().draw(true);
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });
</script>
@endsection